// src/languages.js
export const languages = {
  en: {
    selectLanguage: "Select Language",
    selectRole: "Select Your Role",
    asha: "ASHA",
    phc: "PHC",
    name: "Name",
    phone: "Phone",
    village: "Village",
    centerName: "PHC Center Name",
    inchargeName: "In-charge Name",
    registerASHA: "Register ASHA",
    registerPHC: "Register PHC",
    welcome: "Welcome",
    profile: "Profile",
    saveProfile: "Save Profile",
    householdsVisited: "Households Visited",
    pendingTasks: "Pending Tasks",
    recentVisits: "Recent Visits",
    area: "Area",
    ashaId: "ASHA ID",
    dob: "Date of Birth",
    gender: "Gender",
    email: "Email",
    households: "Households",
    joiningDate: "Joining Date",
    noEntries: "No entries yet",
    addNewEntry: "Add New Entry",
    registerPregnancy: "Register Pregnancy",
    childHealth: "Child Health",
    familyPlanning: "Family Planning",
    diseaseSurveillance: "Disease Surveillance",
    referrals: "Referrals",
    healthAwareness: "Health Awareness",
    saveLocally: "Save Locally",
    syncNow: "Sync Now"
  },
  ta: {
    selectLanguage: "மொழியை தேர்ந்தெடுக்கவும்",
    selectRole: "உங்கள் பங்கை  தேர்ந்தெடுக்கவும்",
    asha: "ஆசா",
    phc: "பிஹெச் சி",
    name: "பெயர்",
    phone: "தொலைபேசி",
    village: "கிராமம்",
    centerName: "PHC மையம் பெயர்",
    inchargeName: "முகாமையாளர் பெயர்",
    registerASHA: "ஆசா பதிவுசெய்",
    registerPHC: "PHC பதிவுசெய்",
    welcome: "வரவேற்பு",
    profile: "சுயவிவரம்",
    saveProfile: "சுயவிவரம் சேமிக்கவும்",
    householdsVisited: "பார்வையிட்ட வீடுகள்",
    pendingTasks: "நிலுவையில் உள்ள பணிகள்",
    recentVisits: "சமீபத்திய பார்வைகள்",
    area: "பகுதி",
    ashaId: "ஆஷா ஐடி",
    dob: "பிறந்த தேதி",
    gender: "பாலினம்",
    email: "மின்னஞ்சல்",
    households: "வீடுகள்",
    joiningDate: "சேர்ந்த தேதி",
    noEntries: "இதுவரை பதிவுகள் இல்லை",
    addNewEntry: "புதிய பதிவு சேர்க்கவும்",
    registerPregnancy: "கர்ப்பப் பதிவு",
    childHealth: "குழந்தை சுகாதாரம்",
    familyPlanning: "குடும்பத் திட்டமிடல்",
    diseaseSurveillance: "நோய் கண்காணிப்பு",
    referrals: "மறுபரிந்துரைகள்",
    healthAwareness: "சுகாதார விழிப்புணர்வு",
    saveLocally: "உள்ளூரில் சேமி",
    syncNow: "இப்போது ஒத்திசை"
  }
};
